spring:
    mustache:
        servlet:
            expose-request-attributes: true
#    security:
#        oauth2:
#            client:
#                registration:
#                    google:
#                        clientId: 510079317475-o58nudcp6fscb1spf4u3uovepoq0uuq8.apps.googleusercontent.com
#                        clientSecret: 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
#                        scope: openid,profile,email,https://www.googleapis.com/auth/youtube
app:
    config:
        header: Greetings Learning Spring Boot 3.0 fans!
        intro: In this chapter, we are learning how to make a web app using Spring Boot 3.0
        users:
            - 
                username: alice
                password: password
                authorities:
                    - ROLE_USER
            -
                username: bob
                password: password
                authorities:
                    - ROLE_USER
            -
                username: admin
                password: password
                authorities:
                    - ROLE_ADMIN

